apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
    apiVersion: v1
    kind: Service
    metadata:
        name: wordpress
        annotations:
          metallb.universe.tf/allow-shared-ip: shared
    spec:
        selector:
            app: wordpress
        ports:
            - name: wordpress
              port: 5050
              protocol: TCP
              targetPort: 5050
        type: LoadBalancer
